dependencies:
  - aave/protocol-v2@1.0.1
compiler:
  solc:
    remappings:
      - '@aave=aave/protocol-v2@1.0.1'
dotenv: .env

networks:
  default: polygon-test

  avax-test:
    # address of lending pool and tokens
    # *see https://docs.aave.com/developers/v/2.0/deployed-contracts/avalanche-market
    lending_pool_addresses_provider: '0x7fdC1FdF79BE3309bf82f4abdAD9f111A6590C0f'
    lending_pool: '0x76cc67FF2CC77821A70ED14321111Ce381C2594D'
    wavax_token : '0xd00ae08403B9bbb9124bB305C09058E32C39A48c'
    weth_token  : '0x9668f5f55f2712Dd2dfa316256609b516292D554'
    # ????
    link_token  : '0x0b9d5D9136855f6FEc3c0993feE6E9CE8a297846' 
    # price-feeds (currency conversion rates):
    # *see https://docs.chain.link/data-feeds/price-feeds/addresses?network=avalanche
    avax_to_usd : '0x5498BB86BC934c8D34FDA08E81D444153d0D06aD'
    eth_to_usd  : '0x86d67c3D38D2bCeE722E601025C25a575021c6EA'
    link_to_avax: '0x79c91fd4F8b3DaBEe17d286EB11cEE4D83521775'
    link_to_usd : '0x34C4c526902d88a3Aa98DB8a9b802603EB1E3470'

    FlashLoan_    : "0x27293280A84c5A57b16487Db9D7f57DB6f521E63"

  polygon-test:
    # address of lending pool and tokens
    # *see https://docs.aave.com/developers/v/2.0/deployed-contracts/matic-polygon-market
    lending_pool_addresses_provider: '0x178113104fEcbcD7fF8669a0150721e231F0FD4B'
    lending_pool: '0x9198F13B08E299d85E096929fA9781A1E3d5d827'
    # AAVE Token contract addresses [from same webpage as above]
    aMatic_token : '0xF45444171435d0aCB08a8af493837eF18e86EE27'
    aWeth_token  : '0x7aE20397Ca327721F013BB9e140C707F82871b56'
    StableWeth   : '0x35D88812d32b966da90db9F546fbf43553C4F35b'
    StableMatic  : '0xfeedbD76ac61616f270911CCaBb43a36380f40ae'
    #
    weth_token   : '0xA6FA4fB5f76172d178d61B04b0ecd319C5d1C0aa'
    WMatic_token : '0x9c3C9283D3e44854697Cd22D3Faa240Cfb032889'
    # for Link token see https://docs.chain.link/resources/link-token-contracts#mumbai-testnet
    link_token   : '0x326C977E6efc84E512bB9C30f76E30c160eD06FB'

    # price-feeds (currency conversion rates):
    # *see https://docs.chain.link/data-feeds/price-feeds/addresses?network=polygon
    matic_to_usd  : '0xd0D5e3DB44DE05E9F294BB0a3bEEaF030DE24Ada'
    eth_to_usd    : '0x0715A7794a1dc8e42615F059dD6e406A6594651A'
    link_to_matic : '0x12162c3E810393dEC01362aBf156D7ecf6159528'
    link_to_usd   : '0x1C2252aeeD50e0c9B64bDfF2735Ee3C932F5C408'

    # our deployment
    FlashLoan_    : "0x27293280A84c5A57b16487Db9D7f57DB6f521E63"
  
  sepolia:
    testing_  : "test.sol contract address."


 


wallets:
  from_key: ${PRIVATE_KEY}
